[package]
name = "TorrentUtilsR"
version = "0.2.2"
edition = "2024"

[dependencies]
argh = "0.1.13"
chrono = "0.4.41"
hex = "0.4.3"
indicatif = "0.18.0"
natord = "1.0.9"
serde = { version = "1.0.219", features = ["derive"] }
sha1 = "0.10.6"
toml = "0.9.5"
walkdir = "2.5.0"
