[package]
name = "TorrentUtilsR"
version = "0.1.5"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.45", features = ["derive"] }
hex = "0.4.3"
indicatif = "0.18.0"
serde = { version = "1.0.219", features = ["derive"] }
sha1 = "0.10.6"
toml = "0.9.5"
walkdir = "2.5.0"
