name: _build

on:
  workflow_call:
    inputs:
      bin_name:
        required: true
        type: string
      release_tag:
        required: false
        default: ""
        type: string

permissions:
  contents: write

env:
  BIN_NAME: ${{ inputs.bin_name }}
  CARGO_TERM_COLOR: always

jobs:
  build-matrix:
    name: build (${{ matrix.target }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025
            target: x86_64-pc-windows-msvc
          - os: windows-11-arm
            target: aarch64-pc-windows-msvc
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
          - os: macos-15
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install musl-tools
        if: matrix.os == 'ubuntu-24.04'
        run: sudo apt-get install -y musl-tools

      - name: Install UPX
        if: matrix.os == 'windows-2025' || matrix.os == 'ubuntu-24.04'
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --target ${{ matrix.target }} --release

      - name: Prepare binary
        shell: bash
        run: |
          set -euo pipefail

          if [ -z "${{ inputs.release_tag }}" ]; then
            STAGING="${{ env.BIN_NAME }}_${{ github.sha }}_${{ matrix.target }}"
          else
            STAGING="${{ env.BIN_NAME }}_${{ inputs.release_tag }}_${{ matrix.target }}"
          fi

          case "${{ matrix.os }}" in
            windows-2025)
              cp "target/${{ matrix.target }}/release/${{ env.BIN_NAME }}.exe" "target/$STAGING.exe"
              upx --best --ultra-brute "target/$STAGING.exe"
              echo "ASSET=target/$STAGING.exe" >> $GITHUB_ENV
              ;;
            windows-11-arm)
              cp "target/${{ matrix.target }}/release/${{ env.BIN_NAME }}.exe" "target/$STAGING.exe"
              echo "ASSET=target/$STAGING.exe" >> $GITHUB_ENV
              ;;
            macos-15)
              cp "target/${{ matrix.target }}/release/${{ env.BIN_NAME }}" "target/$STAGING"
              chmod +x "target/$STAGING"
              echo "ASSET=target/$STAGING" >> $GITHUB_ENV
              ;;
            *)
              # Linux
              cp "target/${{ matrix.target }}/release/${{ env.BIN_NAME }}" "target/$STAGING"
              upx --best --ultra-brute "target/$STAGING"
              echo "ASSET=target/$STAGING" >> $GITHUB_ENV
              ;;
          esac

      - name: Upload artifact
        if: inputs.release_tag == ''
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BIN_NAME }}-${{ matrix.target }}-${{ github.sha }}
          path: ${{ env.ASSET }}
          if-no-files-found: error

      - name: Upload to GitHub Release
        if: inputs.release_tag != ''
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload "${{ inputs.release_tag }}" "${{ env.ASSET }}" --clobber
