name: CI Build

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    if: startsWith(github.ref, 'refs/heads/')
    uses: ./.github/workflows/_build.yml
    with:
      bin_name: TorrentUtilsR
      release_tag: ""
