name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Get tag
        id: tag
        run: echo "tag=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
      - name: Create GitHub release (draft)
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create "${{ steps.tag.outputs.tag }}" --verify-tag --draft --title "${{ steps.tag.outputs.tag }}"

  build-and-upload:
    needs: create-release
    uses: ./.github/workflows/_build.yml
    with:
      bin_name: TorrentUtilsR
      release_tag: ${{ needs.create-release.outputs.tag }}

  publish-release:
    needs: [create-release, build-and-upload]
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release edit "${{ needs.create-release.outputs.tag }}" --draft=false
